/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.snailz.sumtimer;

import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;

/**
 *
 * @author user
 */
public class SumTimer extends javax.swing.JFrame{
    
    private Spell D;
    private Spell F;
    
    private SpellTimer spelltimer;

    /**
     * Creates new form SumTime
     */
    
    public boolean isInteger(String str) {
        if (str == null) {
            return false;
        }
        int length = str.length();
        if (length == 0) {
            return false;
        }
        int i = 0;
        if (str.charAt(0) == '-') {
            if (length == 1) {
                return false;
            }
            i = 1;
        }
        for (; i < length; i++) {
            char c = str.charAt(i);
            if (c < '0' || c > '9') {
                return false;
            }
        }
        return true;
    }
    
    public SumTimer(Spell D, Spell F) {
        initComponents();
        spelltimer = new SpellTimer(DTime, FTime, D, F, 0.0);
        this.addKeyListener(new KeyPressedEvent(spelltimer));
        this.setTitle("Summoner Spell Timer");
        ImageIcon img = new ImageIcon("resources/FLASH.png");
        this.setIconImage(img.getImage());
        this.D = D;
        this.F = F;
        DIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/snailz/sumtimer/resources/" + D.toString() + ".png")));
        FIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/snailz/sumtimer/resources/" + F.toString() + ".png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DIcon = new javax.swing.JLabel();
        FIcon = new javax.swing.JLabel();
        DTime = new javax.swing.JLabel();
        FTime = new javax.swing.JLabel();
        SpellCDR = new javax.swing.JTextField();
        CDRInvalid = new javax.swing.JLabel();
        StartD = new javax.swing.JButton();
        StartF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DIcon.setText("D");

        FIcon.setText("F");

        DTime.setText("D Time");

        FTime.setText("F Time");

        SpellCDR.setText("Spell CDR");
        SpellCDR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpellCDRActionPerformed(evt);
            }
        });

        StartD.setText("Start D");
        StartD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartDActionPerformed(evt);
            }
        });

        StartF.setText("Start F");
        StartF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DIcon)
                    .addComponent(FIcon))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FTime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(StartF))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DTime)
                        .addGap(40, 40, 40)
                        .addComponent(StartD)))
                .addGap(56, 140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SpellCDR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CDRInvalid, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DIcon)
                    .addComponent(DTime)
                    .addComponent(StartD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CDRInvalid, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SpellCDR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FIcon)
                    .addComponent(FTime)
                    .addComponent(StartF))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SpellCDRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpellCDRActionPerformed
        if (isInteger(SpellCDR.getText())){
            spelltimer.setCDR(Integer.parseInt(SpellCDR.getText()));
            CDRInvalid.setText("");
        } else{
            CDRInvalid.setText("Invalid Number!");
        }
    }//GEN-LAST:event_SpellCDRActionPerformed

    private void StartDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartDActionPerformed
        spelltimer.DTime();
    }//GEN-LAST:event_StartDActionPerformed

    private void StartFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartFActionPerformed
        spelltimer.FTime();
    }//GEN-LAST:event_StartFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CDRInvalid;
    private javax.swing.JLabel DIcon;
    private javax.swing.JLabel DTime;
    private javax.swing.JLabel FIcon;
    private javax.swing.JLabel FTime;
    private javax.swing.JTextField SpellCDR;
    private javax.swing.JButton StartD;
    private javax.swing.JButton StartF;
    // End of variables declaration//GEN-END:variables
}
